/**
 * Writes lib/abi.ts from artifacts/CrewPay.json.
 *
 * The app only ever needs the ABI. Importing the artifact JSON directly would
 * drag the creation bytecode into the client bundle for no reason, and the
 * ABI is the one thing that must never drift from what is deployed — so it is
 * generated from the artifact rather than typed out a second time.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { root } from "./lib.mjs";

const artifact = JSON.parse(readFileSync(resolve(root, "artifacts/CrewPay.json"), "utf8"));

const banner = `// Generated by scripts/abi.mjs from artifacts/CrewPay.json — do not edit by hand.
// Regenerate with \`npm run compile\` after any change to contracts/CrewPay.sol.
`;

const body = `export const CREWPAY_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

writeFileSync(resolve(root, "lib/abi.ts"), banner + "\n" + body);
console.log(`wrote lib/abi.ts (${artifact.abi.length} entries)`);
